[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "FuraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.75

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true

[shell]
program = "/usr/bin/tmux"
