#!/bin/bash

# Set root password
sudo passwd root

echo Copying files over
sudo bash -c "cat ~/dotfiles/rc.local > /etc/rc.local"
sudo chmod 760 /etc/rc.local

source ~/.bashrc

echo Updating repo
sudo apt-get update

# Install standard dependencies
echo Installing dependencies
sudo apt -y install gtk2-engines-murrine gtk2-engines-pixbuf libnotify-bin xserver-xorg-input-libinput xinput exfat-fuse exfat-utils imagemagick-6.q16 graphicsmagick-imagemagick-compat imagemagick-6.q16hdri texlive-full unrar p7zip-full python-unidecode xdotool

# Ensure stable release on i3 (Note: this contrains dmenu and i3lock)
/usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2021.02.02_all.deb keyring.deb SHA256:cccfb1dd7d6b1b6a137bb96ea5b5eef18a0a4a6df1d6c0c37832025d2edaa710
sudo dpkg -i ./keyring.deb
sudo echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list
sudo apt update
sudo apt install i3

# Install base apps
echo Installing base apps
sudo apt-get -y install rofi compton lxappearance vim thunar terminator rxvt-unicode feh neofetch python-pip autoconf vifm conky zathura okular

curl https://raw.githubusercontent.com/mina86/urxvt-tabbedex/master/install | sh

# Install i3-gaps
echo Installing i3-gaps
sudo add-apt-repository ppa:kgilmer/speed-ricer
sudo apt-get update
sudo apt install i3-gaps

# Install Vim plugins
echo Installing Vim plugins
git clone https://github.com/jiangmiao/auto-pairs.git   ~/.vim/bundle/auto-pairs
git clone https://github.com/scrooloose/nerdtree.git    ~/.vim/bundle/nerdtree
git clone https://github.com/SirVer/ultisnips.git       ~/.vim/bundle/ultilsnips
git clone https://github.com/honza/vim-snippets.git     ~/.vim/bundle/vim-snippets
git clone https://github.com/VundleVim/Vundle.vim.git   ~/.vim/bundle/Vundle.vim
git clone https://github.com/morhetz/gruvbox.git        ~/.vim/bundle/gruvbox
git clone https://github.com/lervag/vimtex.git          ~/.vim/bundle/vimtex
git clone https://github.com/easymotion/vim-easymotion.git ~/.vim/bundle/vim-easymotion
git clone git://github.com/godlygeek/tabular.git ~/.vim/bundle/tabular
git clone https://github.com/vimwiki/vimwiki.git ~/.vim/bundle/vimwiki
vim +PluginInstall +qall

ln -sf ~/dotfiles/UltiSnips ~/.vim/bundle/vim-snippets/UltiSnips

# Install Polybar
echo "Installing polybar"
sudo apt install polybar

mkdir ~/Apps

# Install dwal
echo "Installing pywal"
sudo apt install pywal

# Install calibre
sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
xdg-mime default okularApplication_pdf.desktop application/pdf

ln -fs ~/dotfiles/.fehbg > ~/.fehbg
ln -fs ~/dotfiles/.vimrc > ~/.vimrc
ln -fs ~/dotfiles/.Xresources > ~/.Xresources
ln -fs ~/dotfiles/.bashrc ~/.bashrc
ln -fs ~/dotfiles/i3/config ~/.config/i3/config
ln -fs ~/dotfiles/Scripts ~/Scripts
ln -fs ~/dotfiles/terminator ~/.config/terminator
ln -fs ~/dotfiles/polybar ~/.config/polybar
ln -fs ~/dotfiles/.local ~/.local
ln -fs ~/dotfiles/.icons ~/.icons
ln -fs ~/dotfiles/.themes ~/.themes
echo "Installation Completed"
