#!/bin/bash

# Set root password
sudo passwd root

echo Copying files over
sudo bash -c "cat ~/dotfiles/rc.local > /etc/rc.local"
sudo chmod 760 /etc/rc.local

cat ~/dotfiles/.fehbg > ~/.fehbg
cat ~/dotfiles/.vimrc > ~/.vimrc
cat ~/dotfiles/.Xresources > ~/.Xresources
cp -r ~/dotfiles/.bashrc ~/
cp -r ~/dotfiles/dunst ~/.config/
cp -r ~/dotfiles/i3 ~/.config/
cp -r ~/dotfiles/Scripts ~/
cp -r ~/dotfiles/terminator ~/.config/
cp -r ~/dotfiles/polybar ~/.config/
cp -r ~/dotfiles/.local ~/
cp -r ~/dotfiles/.icons ~/
cp -r ~/dotfiles/.themes ~/


# Create note directory for notify scripts
mkdir ~/Notes/
touch ~/Notes/notes

source ~/.bahrc

echo Updating repo
sudo apt-get update

# Install standard dependencies
echo Installing dependencies
sudo apt -y install gtk2-engines-murrine gtk2-engines-pixbuf libnotify-bin xserver-xorg-input-libinput xinput exfat-fuse exfat-utils imagemagick-6.q16 graphicsmagick-imagemagick-compat imagemagick-6.q16hdri texlive-full unrar p7zip-full python-unidecode xdotool

# Dunst dependencies
sudo apt -y install libdbus-1-dev libx11-dev libxinerama-dev libxrandr-dev libxss-dev libglib2.0-dev libpango1.0-dev libgtk-3-dev libxdg-basedir-dev

git clone https://github.com/dunst-project/dunst.git ~/.config/dunst
cd ~/.config/dunst/
make
sudo make install
cat ~/dotfiles/dunst/dunstrc > ~/.config/dunst/dunstrc


# Ensure stable release on i3 (Note: this contrains dmenu and i3lock)
sudo /usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb keyring.deb SHA256:176af52de1a976f103f9809920d80d02411ac5e763f695327de9fa6aff23f416
sudo dpkg -i ./keyring.deb
sudo bash -c "echo "deb https://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list"
sudo apt update

# Install base apps
echo Installing base apps
sudo apt-get -y install rofi compton i3 lxappearance vim thunar terminator rxvt-unicode dunst feh neofetch python-pip autoconf vifm conky zathura okular

curl https://raw.githubusercontent.com/mina86/urxvt-tabbedex/master/install | sh

# Install i3-gap dependencies
echo Installing i3-gap dependencies
sudo apt-get -y install libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev autoconf libxcb-xrm0 libxcb-xrm-dev automake libxcb-shape0-dev

# Install i3lock-color (i3lock comes with i3wm)
echo Installing i3lock-color
sudo apt -y install libev-dev libxcb-composite0 libxcb-composite0-dev libxcb-xinerama0 libxcb-randr0 libxcb-xinerama0-dev libxcb-xkb-dev libxcb-image0-dev libxcb-util-dev libxkbcommon-x11-dev libjpeg-turbo8-dev libpam0g-dev

# Install i3-gaps
echo Installing i3-gaps
git clone https://www.github.com/Airblader/i3 ~/.config/i3/i3-gaps
cd ~/.config/i3/i3-gaps/
autoreconf --force --install
rm -rf build/
mkdir -p build && cd build/
../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
make 
sudo make install

# Install i3lock-color
echo Installing i3lock-color
git clone https://github.com/PandorasFox/i3lock-color.git ~/.config/i3/i3lock-color
cd ~/.config/i3/i3lock-color
autoreconf --force --install
rm -rf build/
mkdir -p build && cd build/

../configure \
  --prefix=/usr \
  --sysconfdir=/etc \
  --disable-sanitizers
make
cat ~/dotfiles/i3/lock.sh > ~/.config/i3/i3lock-color/lock.sh

# Install i3lock-fancy
echo Installing i3lock-fancy
git clone https://github.com/meskarune/i3lock-fancy.git ~/.config/i3/i3lock-fancy
cd ~/.config/i3/i3lock-fancy
sudo make install
cat ~/dotfiles/scripts/i3lock-fancy > ~/.config/i3/i3lock-fancy/i3lock-fancy

# Install Vim plugins
echo Installing Vim plugins
git clone https://github.com/jiangmiao/auto-pairs.git   ~/.vim/bundle/auto-pairs
git clone https://github.com/scrooloose/nerdtree.git    ~/.vim/bundle/nerdtree
git clone https://github.com/SirVer/ultisnips.git       ~/.vim/bundle/ultilsnips
git clone https://github.com/honza/vim-snippets.git     ~/.vim/bundle/vim-snippets
git clone https://github.com/VundleVim/Vundle.vim.git   ~/.vim/bundle/Vundle.vim
git clone https://github.com/morhetz/gruvbox.git        ~/.vim/bundle/gruvbox
git clone https://github.com/lervag/vimtex.git          ~/.vim/bundle/vimtex
git clone https://github.com/easymotion/vim-easymotion.git ~/.vim/bundle/vim-easymotion
git clone https://github.com/dhruvasagar/vim-table-mode.git ~/.vim/bundle/vim-table-mode
git clone git://github.com/godlygeek/tabular.git ~/.vim/bundle/tabular
git clone https://github.com/vimwiki/vimwiki.git ~/.vim/bundle/vimwiki
git clone https://github.com/plasticboy/vim-markdown.git ~/.vim/bundle/vim-markdown

vim +PluginInstall +qall

cp -r ~/dotfiles/UltiSnips/ ~/.vim/bundle/vim-snippets/

# Install Polybar
echo Installing Polybar
sudo apt-get -y install cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xkb-dev pkg-config python-xcbgen xcb-proto libxcb-xrm-dev i3-wm libasound2-dev libmpdclient-dev libiw-dev libcurl4-openssl-dev libpulse-dev libxcb-composite0-dev xcb libxcb-ewmh2
git clone https://github.com/jaagr/polybar.git ~/.config/i3/polybar
cd ~/.config/i3/polybar && ./build.sh

# Install java 8
echo Installing Java-8
sudo apt install openjdk-8-jdk openjdk-8-jre
sudo cat >> /etc/environment <<EOL
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
JRE_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
EOL

mkdir ~/Apps

# Install dwal
git clone https://github.com/adi1090x/dynamic-wallpaper.git ~/Apps/dwal
chmod +x ~/Apps/install.sh
~/Apps/install.sh

# Install calibre
sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
xdg-mime default okularApplication_pdf.desktop application/pdf

echo "Installation Completed"
