#!/bin/bash

echo -n "Enter username: "
read username

path="/home/blank/"
if id $username &> /dev/null ; then
    path="/home/${username}/"
else
    echo "This is not a user. Exitting."
    exit
fi

# Set root password
sudo passwd root


echo Updating repo
sudo apt-get update

# Install standard dependencies
echo Installing dependencies
sudo apt -y install curl gtk2-engines-murrine gtk2-engines-pixbuf libnotify-bin xserver-xorg-input-libinput xinput exfat-fuse exfat-utils graphicsmagick-imagemagick-compat unrar p7zip-full xdotool 

# Ensure stable release on i3 (Note: this contrains dmenu and i3lock) Feb. 2021 version
/usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2021.02.02_all.deb keyring.deb SHA256:cccfb1dd7d6b1b6a137bb96ea5b5eef18a0a4a6df1d6c0c37832025d2edaa710
sudo dpkg -i ./keyring.deb
sudo echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list
sudo apt update

# Install base apps
echo Installing base apps
sudo apt-get -y install rofi compton lxappearance vim thunar terminator rxvt-unicode feh neofetch autoconf vifm conky zathura okular curl

curl https://raw.githubusercontent.com/mina86/urxvt-tabbedex/master/install | sh

# Install i3-gaps
echo Installing i3-gaps
sudo add-apt-repository ppa:kgilmer/speed-ricer
sudo apt-get update
sudo apt install i3-gaps-wm
sudo apt install i3-wm
sudo apt install i3-gaps
sudo apt install i3

# Install Vim plugins
echo Installing Vim plugins
git clone https://github.com/jiangmiao/auto-pairs.git   ~/.vim/bundle/auto-pairs
git clone https://github.com/scrooloose/nerdtree.git    ~/.vim/bundle/nerdtree
git clone https://github.com/SirVer/ultisnips.git       ~/.vim/bundle/ultilsnips
git clone https://github.com/honza/vim-snippets.git     ~/.vim/bundle/vim-snippets
git clone https://github.com/VundleVim/Vundle.vim.git   ~/.vim/bundle/Vundle.vim
git clone https://github.com/morhetz/gruvbox.git        ~/.vim/bundle/gruvbox
git clone https://github.com/lervag/vimtex.git          ~/.vim/bundle/vimtex
git clone https://github.com/easymotion/vim-easymotion.git ~/.vim/bundle/vim-easymotion
git clone git://github.com/godlygeek/tabular.git ~/.vim/bundle/tabular
git clone https://github.com/vimwiki/vimwiki.git ~/.vim/bundle/vimwiki
vim +PluginInstall +qall

ln -sf ~/dotfiles/UltiSnips ~/.vim/bundle/vim-snippets/UltiSnips

# Install Polybar
echo "Installing polybar"
sudo apt install polybar

mkdir ~/Apps

# Install dwal
echo "Installing pywal"
echo "Installing pywal"
sudo apt-get install x11-xserver-utils feh cron
mkdir "${path}Apps/"
git clone https://github.com/adi1090x/dynamic-wallpaper.git "${path}Apps/"
chmod +x "${path}Apps/dwal/install.sh"
eval "${path}Apps/dwal/install.sh"

# Install calibre
sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
xdg-mime default okularApplication_pdf.desktop application/pdf

mkdir "${path}.config/i3"

ln -fs "${path}dotfiles/.fehbg" "${path}"
ln -fs "${path}dotfiles/.vimrc" "${path}"
ln -fs "${path}dotfiles/.Xresources" "${path}"
ln -fs "${path}dotfiles/.bashrc" "${path}.bashrc"
ln -fs "${path}dotfiles/i3/config" "${path}.config/i3/"
ln -fs "${path}dotfiles/Scripts" "${path}"
ln -fs "${path}dotfiles/polybar" "${path}.config/"
ln -fs "${path}dotfiles/.local" "${path}"
ln -fs "${path}dotfiles/.icons" "${path}"
ln -fs "${path}dotfiles/.themes" "${path}"

xrdb ~/.Xresources
source ~/.bashrc
echo "Installation Completed"
