#!/bin/bash

# This is how you would install I install Qtile on Ubuntu
# Putting Qtile in it's own environment https://whatacold.io/blog/2019-09-29-how-to-run-the-bleeding-edge-code-of-qtile/

USER=$(whoami)

# Install Python
sudo apt-get install python3.8 python3.8-dev pyhon3.8-venv

# Get qtile
mkdir -p ~/local/
git clone https://github.com/qtile/qtile.git

# Create and enter python3.8 environment
python3.8 -m venv ~/local/qtile/qtile-env/
source ~/local/qtile/qtile-env/bin/activate

# Install dependencies
python3.8 -m pip install xcffib psutil finnhub-python
python3.8 -m pip install --no-cache-dir cairocffi

cat > /home/$USER/local/qtile/qtile-venv-entry <<EOF
#!/bin/bash

# This glue shell is only needed when you want to
# run Qtile within a virtualenv

source ~/local/qtile/qtile-env/bin/activate
python ~/local/qtile/bin/qtile $*
EOF

chmod +x /home/$USER/local/qtile/qtile-venv-entry
sudo cat > /usr/share/xsessions/qtile-venv.desktop <<EOF
Name=Qtile(venv)
Comment=Qtile Session Within Venv
Exec=/home/foo/local/qtile/qtile-venv-entry
Type=Application
Keywords=wm;tiling
EOF


