# Catppuccin Mocha — for hyprland
$background = rgba(30,30,46,0.94)
$foreground = rgb(cdd6f4)
$color0 = rgb(313244)
$color1 = rgb(f38ba8)
$color2 = rgb(a6e3a1)
$color3 = rgb(f9e2af)
$color4 = rgb(89b4fa)
$color5 = rgb(f5c2e7)
$color6 = rgb(94e2d5)
$color7 = rgb(cdd6f4)
$color8 = rgb(45475a)
$color9 = rgb(f38ba8)
$color10 = rgb(a6e3a1)
$color11 = rgb(cba6f7)
$color12 = rgb(89b4fa)
$color13 = rgb(b4befe)
$color14 = rgb(94e2d5)
$color15 = rgb(cdd6f4)
