alias ls 'eza -F -H --group-directories-first'
alias ll 'ls -alF --long --smart-group'
alias la 'ls -A'
alias l 'ls -CF'
alias lv 'ls -v'
alias cd. 'cd ..'
alias vim 'nvim'
alias vi 'nvim'
alias sof 'source ~/.config/fish/config.fish && notify-send "Updated" "Fish shell updated!" -i terminal'
alias sus 'systemctl suspend'
alias frc 'vi ~/.config/fish/config.fish'
alias vifm. 'vifm .'
alias rebootw 'sudo grub-reboot 2 && reboot'
alias restart_audio 'pulseaudio -k && sudo alsa force-reload'
alias xclip 'xclip -se clipboard'
alias Qtile 'source ~/Apps/qtile/qtile-venv/bin/activate.fish; startx'
alias bssh 'bash ~/Work/better-server-ssh/bssh.sh'
alias dot 'cd ~/dotfiles'
alias tm 'tmux'
alias o 'cd ~/vault'
alias of 'vi ~/vault'
alias to 'z'
alias dotfiles='/usr/bin/git --work-tree=$HOME/dotfiles status'
