#!/usr/bin/env bash
set -euo pipefail

# Where we store the generated xrandr layout
BASE_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/qtile/screenlayout"
PROFILE="${BASE_DIR}/current.sh"

mkdir -p "$BASE_DIR"

if ! command -v xrandr >/dev/null 2>&1; then
  echo "ERROR: xrandr not found. Are you on X11?" >&2
  exit 1
fi

# Get connected outputs (e.g., eDP-1, HDMI-1, DP-1)
# This matches lines like: "HDMI-1 connected ..." (ignores "disconnected")
mapfile -t CONNECTED < <(xrandr --query | awk '$2=="connected"{print $1}')

if [[ ${#CONNECTED[@]} -eq 0 ]]; then
  echo "ERROR: No connected outputs detected by xrandr." >&2
  exit 1
fi

# Prefer eDP* as primary if present (common laptop panel). Else use first connected.
PRIMARY=""
for o in "${CONNECTED[@]}"; do
  if [[ "$o" == eDP-* || "$o" == LVDS-* ]]; then
    PRIMARY="$o"
    break
  fi
done
if [[ -z "$PRIMARY" ]]; then
  PRIMARY="${CONNECTED[0]}"
fi

# Build a simple layout:
# - Turn off ALL outputs first (so stale ones don’t linger)
# - Enable all connected outputs
# - Set PRIMARY as primary
# - Place remaining outputs to the above of the previous enabled output
#
# You can customize placement rules later (below).

# Connected outputs only
mapfile -t CONNECTED < <(
  xrandr --query |
    awk '$2=="connected"{print $1}' |
    awk '!seen[$0]++'
)

if [[ ${#CONNECTED[@]} -eq 0 ]]; then
  echo "ERROR: No connected outputs detected." >&2
  exit 1
fi

# Choose primary: prefer eDP*/LVDS* if present, else first connected
PRIMARY=""
for o in "${CONNECTED[@]}"; do
  if [[ "$o" == eDP-* || "$o" == LVDS-* ]]; then
    PRIMARY="$o"
    break
  fi
done
[[ -z "$PRIMARY" ]] && PRIMARY="${CONNECTED[0]}"

# Build xrandr command with ONE clause per output
XRANDR_CMD=(xrandr)

# Place primary first (so "prev" starts clean)
XRANDR_CMD+=(--output "$PRIMARY" --auto --primary)
prev="$PRIMARY"

# Place others relative to prev (pick one: --right-of / --left-of / --above / --below)
for out in "${CONNECTED[@]}"; do
  [[ "$out" == "$PRIMARY" ]] && continue
  XRANDR_CMD+=(--output "$out" --auto --above "$prev")
  prev="$out"
done

# Write profile file
tmp="$(mktemp)"
cat > "$tmp" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Generated by detect_and_save.sh on $(date -Is)
# Connected outputs at generation time:
#   ${CONNECTED[*]}
# Primary:
#   ${PRIMARY}

$(printf '%q ' "${XRANDR_CMD[@]}")
echo
EOF

chmod +x "$tmp"

mv "$tmp" "$PROFILE"

echo "Saved layout to: $PROFILE"
echo "To apply now: $PROFILE"
