#!/bin/bash
 
#################################
# Author: Khanh Vong
# Date: 3/8/18
# Class: CS2750
# Project: Assignment3_dir-tree
#################################

#initialize path
PATH=/bin:/usr/bin

#function to create tree
intoTree()
{
find $1 | sort | grep -v "/\." | sed 's.[^/]*/.|---.g' | sed 's.[^|]*|.     |.g' | sed 's/^[^|]*|/|/'
}

#if statement to check user input
[[ $# -eq 0 ]] && arg="." || arg="$1"
intoTree $arg

