#!/bin/bash

# A dmenu script for power options

who=$(whoami)
if [ "$who" == "root" ];then
    echo "$0: Not for root usage."
    exit 1
else
    option=$(echo -e "Logoff\nPoweroff\nReboot\nSleep" | dmenu -fn "System San Francisco Display Regular-13" -nb "#1F1F1F" -nf "#FFFFFF" -sb "#515151" -sf "#F1F1F1" -i -p "Power Option:")
    case "$option" in
            Logoff)
                pkill -KILL -u blank
                ;;
            Poweroff)
                poweroff
                ;;
            Reboot)
                reboot
                ;;
            Sleep)
                /home/blank/Scripts/i3lock-fancy -gp && systemctl suspend && pactl set-sink-mute 0 toggle
                ;;
            *)
                exit 1
    esac
fi
