#!/bin/bash

PICTURE=/tmp/i3lock.png
SCREENSHOT="scrot $PICTURE"

BLUR="5x4"

$SCREENSHOT

# Blur
#convert $PICTURE -blur $BLUR $PICTURE

# Block blur
convert $PICTURE -scale 10% -scale 1000% $PICTURE
i3lock -e -i $PICTURE
rm $PICTURE

