#!/bin/bash

#check for number of argument(s)

maxBright=$(cat /sys/class/backlight/intel_backlight/max_brightness)
actBright=$(cat /sys/class/backlight/intel_backlight/actual_brightness)
curBright=$(cat /sys/class/backlight/intel_backlight/brightness)

if [ $# -eq 0 ]; then
    echo Max brightness = $maxBright
    echo Actual brightness = $actBright
    echo Current brightness = $curBright
elif [ $# -gt 1 ]; then
    echo "Program only accept one argument"
    exit 1
else
    if [ "$1" == "show" ]; then
        echo $((actBright*100/maxBright))%
    elif [ $1 -gt $maxBright ]; then
        echo Use a lower number than $maxBright.
    elif [ $1 -lt 1 ]; then
        echo "Use a higher number for brightness."
    elif [ $1 -gt 0 ] && [ $1 -lt 10 ]; then
        input=$1
        div=$(((maxBright*input)/10))
        echo $div > /sys/class/backlight/intel_backlight/brightness
    else
        echo $1 > /sys/class/backlight/intel_backlight/brightness
    fi
fi

